### PR TITLE
Force Vin_ADC, Vout_ADC and Vout_DAC through the 0,0 point

### LINKED ISSUE #158: Force Voltage calibration line of best fits to pass through (0, 0)
Very low current and voltage calibration seems a little off.

I propose we assume that the voltage plots pass through the (0, 0) point and force the line of best fit to also do the same. As you can see the below line of best fit misses this
image
This should help the low end performance (assuming all hardware models act the same)

As this may potentially skew the top end I propose we add another couple of measurement points from the user

### PR DESCRIPTION
**Pull request by Xenoamor**
This is to resolve #158 

This is completely untested and unfortunately adds a requirement to have numpy installed. I'd rather not risk getting the maths wrong

### CODE REVIEW

**Comment by Xenoamor** [comment]
Nice to see Travis working by the way

**Comment by kanflo** [comment]
Thanks, I will give it a try this week.

**Comment by Xenoamor** [comment]
Looks like it's doing the trick
image
image
image

My V_ADC calibration seems off but I'm not sure if that was my fault or these changes

This hasn't resolved the open circuit current issues though

**Comment by Xenoamor** [comment]
I think us using this only for V_DAC is reinforced by the empirical deductions in [dps-model.h](https://github.com/kanflo/opendps/blob/master/opendps/dps-model.h). The only C value that is close to 0 on all of the devices is `V_DAC_C`

**Comment by kanflo** [comment]
What is the consensus on this PR for those of you who has discussed it in #158?

**Comment by Xenoamor** [comment]
I'm not sure yet. I'm fairly sure this makes sense for the voltage DAC but the current is more difficult as it doesn't start at 0

**Comment by kanflo** [comment]
I need to have a look at forcing V_in on an old DPS. Looking at my original measurements on a now very old (as in number ov HW revisions ago) DPS5005. ADC(V_out) and DAC(V_out) passed through (0, 0) but V_in(ADC) did not:

Screenshot 2019-10-02 at 20 06 50

**Comment by kanflo** [comment]
Oh, forget the above, silly old me :-/

Screenshot 2019-10-02 at 20 08 49

**Comment by Xenoamor** [comment]
I'm still not sure we want this applied to the ADCs. The only instance where I got better results were with V_DAC. The rest seemed worse

**Comment by kanflo** [comment]
Oh? I guess I should redo the original investigation on a brand new DPS5005.

**Comment by JackNewman12** [comment]
Yea. Applying this to the current calibration makes it worse. 

I was thinking rather than choose 0,0 we should measure zero voltage and zero current for a few seconds to find the correct point. 

I've been fiddling with this myself but haven't gotten results I am 100% happy with.

**Pull request merged**
