### PR TITLE
dpsctl.py Python3 compatibility 

### PR DESCRIPTION
**Pull request by koppa**
* I ran 2to3 on the dpsctl code. 
* Code is now compatible to python2 and python3. 
* I added some documentation in README.md.
* Fix the build of emu/ and updated documentation

Currently I only tested the code with the emulator (haven't received the hardware yet).
I would like to do some more work on the control script:

* Create proper python module, to easily script the power supply with python
* Write more documentation and examples

### CODE REVIEW

**Comment by kanflo** [comment]
Thanks! I will take it for a spin on HW next year, ie. later this week ;)

**Comment by Xenoamor** [comment]
Creating a proper python module would be great for writing custom test scripts and dataloggers and the such

**Comment by kanflo** [comment]
Hmmm, I am at loss about where the uhej changes ended up. Anyone have any clue?

**Comment by Xenoamor** [comment]
It was a submodule of [this commit](https://github.com/kanflo/opendps/pull/64/commits/ea0a0c396d280014305feca6f15c6fab759175f0) of this pull request. I'm not sure quite what it's for mind

**Pull request merged**
