### PR TITLE
Added support for DPS5020

### PR DESCRIPTION
**Pull request by lukedempsey**

### CODE REVIEW

**Comment by iz3man** [comment]
Any updates on this? I got a 5020 here and could test it if there is a version to test.
Thanks

**Comment by polihedron** [comment]
One week testing, no problems so far, my pcb version v2.5, my calibration factors:
 
A_ADC_K (float)6.7657399f
A_ADC_C (float)-411.87387f
A_DAC_K (float)0.166947f
A_DAC_C (float)251.526f
V_ADC_K (float)12.912699f
V_ADC_C (float)-180.91670f
V_DAC_K (float)0.07749319f
V_DAC_C (float)10.270299f
VIN_ADC_K (float)16.956f
VIN_ADC_C (float)6.6895f
you probably gonna need a fix if you don't like leading zero displayed: #190
and in my opinion  DPS5020 is more noisy than DPS5015.

**Comment by iz3man** [comment]
So you say 5020 is working? How do I have to configure and install it? I only know install of 5005 version. And i just did "regular" standard install, and now i can only set 5A max, and when i turn it on it outputs zero volts and fan goes off.

**Comment by Xenoamor** [comment]
Will probably want to update the build script to generate the firmware for it:
https://github.com/kanflo/opendps/blob/master/docker/build.sh

**Comment by polihedron** [comment]
@iz3man,
or modify Makefile in build model section, and make sure that you have those PR:
#200, #201, #203, not necessary only if you want #190,
then:
make clean
make -C libopencm3
make -C opendps flash
make -C dpsboot flash

**Comment by iz3man** [comment]
I also find out that you need to edit the Makefile (i wasn't aware that every power supply needs it's special version). I tried setting model to 5020 but it was not excepted. 
Does it even support 20A current now - just to be sure before I invest some more hours to find out it's only 80% useable ;)

**Comment by iz3man** [comment]
Or let's try something different: Would anyone of you be so kind to send me the already compiled known working version for the 5020? That would be awesome!

**Comment by iz3man** [comment]
@polihedron Thank you! I have to admit I'm not too familiar with handling github, but I guess you merged all PRs to one big one which should be run against the latest git. Correct?
If so, I have to check how to do that - never did anything like that before.
Then I can change the model in Makefile in /opendps to DPS5020 and it should compile (make -C opendps flash) the correct firmware for the 5020? 
When I do this now it throws some error message, and it c&p all that stuff by hand and may have a typo somewhere. I'm 100% sure there are better ways to do it ;)

**Comment by iz3man** [comment]
Ha! Wait, I guess i found an easier solution: You made a DPS5020 branch in your repository. I clone that one, and I should be fine. Correct?

image

Much appreciated!!

**Comment by iz3man** [comment]
@polihedron Thanks a lot. I managed to flash my DPS5020 now, and it works.
Just need to make some calibration now, as 5V output 5.2V and setting current is a bit cumbersome as it starts with the second digit (10, 20A). Would be easier to adjust the first digit (0-9A and then dial up to 10+).

**Comment by polihedron** [comment]
Glad you made it, what version pcb you have? 
My calibration factors where made at 5-8A load current, so when you measure output voltage at 0A then probably voltage is a bit higher than set.
Regarding to current digits, check description at the most bottom of the function files, probably if you add in func_cv.c: 
cv_current.cur_digit = 2;
just after:
number_init(&cv_current);
then it will be working the same, as for voltage digits.

**Comment by iz3man** [comment]
Worked perfectly fine. Did the same to func_cl.c and func_cc.c
Happy now :)

**Comment by ilium007** [comment]
How do I include #200, #201, #203, #190 if I want to compile for the DOS5020

**Comment by kanflo** [comment]
Closing as this got included in #201

**Pull request closed without merging**
