### PR TITLE
dpsctl.py  PEP8 and cleanup

### PR DESCRIPTION
**Pull request by Cabalist**
I've been enjoying all the new development that has been happening on this codebase.  The UI looks great!  

This PR is basically just a cleanup of some of the Python code.   I tried to break each change into a separate commit so that it would be easier to review.   There shouldn't be any functionality changes (besides fixing a couple bugs that were revealed by removing `import *` )

### CODE REVIEW

**Comment by Xenoamor** [comment]
Wow this is quite the change list! I'll have to have a read up on PEP8 as I'm not familiar with it and I wouldn't want to undo any of this work with my future work.
The new division method of python 3 is interesting for sure

**Comment by Cabalist** [comment]
@Xenoamor Let me know if you have any question.  I'm happy to clarify anything.   :)

If this is welcome I can attack uHeJ as well.

**Comment by Xenoamor** [comment]
Have you had a chance to look at this @kanflo? I'm hesitant to make any python changes myself at the moment if we're going to adopt a more organised structure

**Comment by kanflo** [comment]
Thanks a lot @Cabalist! I will review this in a day or two.

**Comment by kanflo** [comment]
I only found one small issue and improved my git-fu in the process!

**Comment by Cabalist** [comment]
Nice.   Good catch.    That would be different in Python 2/3 as well.

**Comment by kanflo** [comment]
Oh? Bummer ;)

**Pull request merged**
