### PR TITLE
Zero-out DAC values when powering off.

### PR DESCRIPTION
**Pull request by tzarc**
As per comments on https://github.com/kanflo/opendps/issues/36.

### CODE REVIEW

**Comment by kanflo** [comment]
Thanks, I'll try this out when I'm back next week.

**Comment by jimmyw** [comment]
I can confirm that this solves issue #36 for me.

Leaving i_out floating did not cut power for me. It also left me in an endless loop trigering OCP if to low, and not giving me a chance to chang it. Recommends:

diff --git opendps/hw.c opendps/hw.c
index b49682a..14c87ba 100644
--- opendps/hw.c
+++ opendps/hw.c
@@ -262,7 +262,7 @@ void adc1_2_isr(void)
             measure_i_out = false;
         }
     }
-    if (pwrctl_i_limit_raw) {
+    if (pwrctl_i_limit_raw && pwrctl_vout_enabled()) {
         if (adc_counter >= STARTUP_SKIP_COUNT) {
             i += adc_i_offset;
             if (i > pwrctl_i_limit_raw) { /** OCP! */

To solv that.

**Comment by kanflo** [comment]
@tzarc, could you please try the suggestion from @jimmyw?

**Comment by jimmyw** [comment]
My patch did unfortenally stop meassuring adc when hit OCP, better fix is:

```
diff --git opendps/hw.c opendps/hw.c
index b49682a..14c87ba 100644
--- opendps/hw.c
+++ opendps/hw.c
@@ -262,7 +262,7 @@ void adc1_2_isr(void)
             measure_i_out = false;
         }
     }

     if (pwrctl_i_limit_raw) {
         if (adc_counter >= STARTUP_SKIP_COUNT) {
             i += adc_i_offset;
-             if (i > pwrctl_i_limit_raw) { /** OCP! */
+             if (i > pwrctl_i_limit_raw && pwrctl_vout_enabled()) { /** OCP! */
```

**Comment by tzarc** [comment]
I'd test it, but my "working" branch results in a black screen after updating.
I guess it's something to do with the compiler, will probably create a standardised docker build "instance" which eliminates versioning issues and the like.

Will see what I can do.

**Comment by tzarc** [comment]
Serves me right for not pulling from upstream... you already have a docker build!
Built and tested, my master branch working fine, branch updated.

**Pull request merged**
