### PR TITLE
Add support for debouncing the buttons

### LINKED ISSUE #88: Need a debounce on buttons
Sometimes hitting power button doesn't register, and it flips itself back on or off if it happens too quickly.

### PR DESCRIPTION
**Pull request by X-Ryl669**
This fix #88 
It ensure that 30ms have passed since last button falling edge (and it doesn't, it skip the action for the button press). If it has passed 30ms, then it remembers the new timestamp, and the same logic apply.

### CODE REVIEW

**Comment by kanflo** [comment]
Much appreciated. It seems this change is also on your funcGen branch if I am not mistaken.

**Comment by X-Ryl669** [comment]
Yes, sorry, I've not restarted from master. It's easy to revert if you don't like it.

**Comment by kanflo** [comment]
Oh, now worries. I was going to pull your debounce fix anyhow.

**Comment by kanflo** [comment]
Included in #148

**Pull request closed without merging**
